from __future__ import annotations

from typing import overload, Callable, Union, List, Any


class HTMLCollection:
    def __itter__(self) -> HTMLCollection:...
    def __next__(self) -> HTMLEllement:...
    def __len__(self) -> int:...
    def length(self) -> int:...

class HTMLElement:
    @property
    def id(self) -> int:...
    @property
    def name(self) -> str:...
    @property
    def class(self) -> str:...
    @property
    def children(self) -> HTMLCollection:...
    @property
    def hidden(self) -> bool:...
    @property
    def innerText(self) -> str:...
    @property
    def inner_text(self) -> str:...
    @property
    def style(self) -> Dict[str, Union[Any]]:...
    @property
    def click(self) -> None:...

